In [1]:
import pandas as pd

application = pd.read_csv("dataset/application_record.csv")
credit = pd.read_csv("dataset/credit_record.csv")

print("Application Shape:", application.shape)
print("Credit Shape:", credit.shape)

application.head()

Application Shape: (438557, 18)
Credit Shape: (1048575, 3)

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2.0
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0

In [2]:
print("Application Dataset Information")
application.info()

print("\n" + "="*50 + "\n")

print("Credit Dataset Information")
credit.info()

Application Dataset Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438557 entries, 0 to 438556
Data columns (total 18 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ID                   438557 non-null  int64
 1   CODE_GENDER          438557 non-null  object
 2   FLAG_OWN_CAR         438557 non-null  object
 3   FLAG_OWN_REALTY      438557 non-null  object
 4   CNT_CHILDREN         438557 non-null  int64
 5   AMT_INCOME_TOTAL     438557 non-null  float64
 6   NAME_INCOME_TYPE     438557 non-null  object
 7   NAME_EDUCATION_TYPE  438557 non-null  object
 8   NAME_FAMILY_STATUS   438557 non-null  object
 9   NAME_HOUSING_TYPE    438557 non-null  object
 10  DAYS_BIRTH           438557 non-null  int64
 11  DAYS_EMPLOYED        438557 non-null  int64
 12  FLAG_MOBIL           438557 non-null  int64
 13  FLAG_WORK_PHONE      438557 non-null  int64
 14  FLAG_PHONE           438557 non-null  int64
 15  FLAG_EMAIL           438557 non-null  int64
 16  OCCUPATION_TYPE      304354 non-null  object
 17  CNT_FAM_MEMBERS      438557 non-null  float64
dtypes: float64(2), int64(8), object(8)
memory usage: 60.2+ MB

==================================================

Credit Dataset Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 3 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   ID              1048575 non-null  int64
 1   MONTHS_BALANCE  1048575 non-null  int64
 2   STATUS          1048575 non-null  object
dtypes: int64(2), object(1)
memory usage: 24.0+ MB

In [3]:
application.describe()

,ID,CNT_CHILDREN,AMT_INCOME_TOTAL,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,CNT_FAM_MEMBERS
count,4.385570e+05,438557.000000,4.385570e+05,438557.000000,438557.000000,438557.0,438557.000000,438557.000000,438557.000000,438557.000000
mean,6.022176e+06,0.427390,1.875243e+05,-15997.904649,60563.675328,1.0,0.206133,0.287771,0.108207,2.194465
std,5.716370e+05,0.724882,1.100869e+05,4185.030007,138767.799647,0.0,0.404527,0.452724,0.310642,0.897207
min,5.008804e+06,0.000000,2.610000e+04,-25201.000000,-17531.000000,1.0,0.000000,0.000000,0.000000,1.000000
25%,5.609375e+06,0.000000,1.215000e+05,-19483.000000,-3103.000000,1.0,0.000000,0.000000,0.000000,2.000000
50%,6.047745e+06,0.000000,1.607805e+05,-15630.000000,-1467.000000,1.0,0.000000,0.000000,0.000000,2.000000
75%,6.456971e+06,1.000000,2.250000e+05,-12514.000000,-371.000000,1.0,0.000000,1.000000,0.000000,3.000000
max,7.999952e+06,19.000000,6.750000e+06,-7489.000000,365243.000000,1.0,1.000000,1.000000,1.000000,20.000000

In [4]:
application.describe(include="object")

,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,OCCUPATION_TYPE
count,438557,438557,438557,438557,438557,438557,438557,304354
unique,2,2,2,5,5,5,6,18
top,F,N,Y,Working,Secondary / secondary special,Married,House / apartment,Laborers
freq,294440,275459,304074,226104,301821,299828,393831,78240

In [5]:
application.isnull().sum()

ID                          0
CODE_GENDER                 0
FLAG_OWN_CAR                0
FLAG_OWN_REALTY             0
CNT_CHILDREN                0
AMT_INCOME_TOTAL            0
NAME_INCOME_TYPE            0
NAME_EDUCATION_TYPE         0
NAME_FAMILY_STATUS          0
NAME_HOUSING_TYPE           0
DAYS_BIRTH                  0
DAYS_EMPLOYED               0
FLAG_MOBIL                  0
FLAG_WORK_PHONE             0
FLAG_PHONE                  0
FLAG_EMAIL                  0
OCCUPATION_TYPE        134203
CNT_FAM_MEMBERS             0
dtype: int64

In [6]:
credit.isnull().sum()

ID                0
MONTHS_BALANCE    0
STATUS            0
dtype: int64

In [7]:
application.columns

Index(['ID', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN',
       'AMT_INCOME_TOTAL', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'DAYS_BIRTH',
       'DAYS_EMPLOYED', 'FLAG_MOBIL', 'FLAG_WORK_PHONE', 'FLAG_PHONE',
       'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS'],
      dtype='object')

In [8]:
credit["STATUS"].value_counts()

STATUS
C    442031
0    383120
X    209230
1     11090
5      1693
2       868
3       320
4       223
Name: count, dtype: int64

In [9]:
credit.head(10)

        ID  MONTHS_BALANCE STATUS
0  5001711               0      X
1  5001711              -1      0
2  5001711              -2      0
3  5001711              -3      0
4  5001712               0      C
5  5001712              -1      C
6  5001712              -2      C
7  5001712              -3      C
8  5001712              -4      C
9  5001712              -5      C

In [10]:
print("Unique customers in application:", application["ID"].nunique())
print("Unique customers in credit:", credit["ID"].nunique())

Unique customers in application: 438510
Unique customers in credit: 45985

In [11]:
credit.groupby("ID")["STATUS"].unique().head(10)

ID
5001711          [X, 0]
5001712          [C, 0]
5001713             [X]
5001714             [X]
5001715             [X]
5001717          [C, 0]
5001718    [C, 0, 1, X]
5001719          [C, 0]
5001720          [1, 0]
5001723          [X, 0]
Name: STATUS, dtype: object

In [12]:
# Customers with any overdue status (1,2,3,4,5) are marked as Bad

bad_status = ['1', '2', '3', '4', '5']

customer_status = credit.groupby("ID")["STATUS"].apply(list).reset_index()

customer_status["TARGET"] = customer_status["STATUS"].apply(
    lambda x: 1 if any(status in bad_status for status in x) else 0
)

customer_status.head(10)

        ID                                             STATUS  TARGET
0  5001711                                       [X, 0, 0, 0]       0
1  5001712  [C, C, C, C, C, C, C, C, C, 0, 0, 0, 0, 0, 0, ...       0
2  5001713  [X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, ...       0
3  5001714      [X, X, X, X, X, X, X, X, X, X, X, X, X, X, X]       0
4  5001715  [X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, ...       0
5  5001717  [C, C, C, C, C, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...       0
6  5001718  [C, C, C, 0, 0, 0, 0, 0, 1, X, 0, X, 1, X, 0, ...       1
7  5001719  [C, C, C, C, C, C, C, C, C, C, C, C, C, C, C, ...       0
8  5001720  [1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, ...       1
9  5001723  [X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, ...       0

In [13]:
customer_status["TARGET"].value_counts()

TARGET
0    40635
1     5350
Name: count, dtype: int64

In [14]:
data = application.merge(customer_status[["ID", "TARGET"]], on="ID", how="inner")

print(data.shape)
data.head()

(36457, 19)

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,TARGET
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,1
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0,1
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2.0,0
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0,0
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0,0

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36457 entries, 0 to 36456
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   36457 non-null  int64
 1   CODE_GENDER          36457 non-null  object
 2   FLAG_OWN_CAR         36457 non-null  object
 3   FLAG_OWN_REALTY      36457 non-null  object
 4   CNT_CHILDREN         36457 non-null  int64
 5   AMT_INCOME_TOTAL     36457 non-null  float64
 6   NAME_INCOME_TYPE     36457 non-null  object
 7   NAME_EDUCATION_TYPE  36457 non-null  object
 8   NAME_FAMILY_STATUS   36457 non-null  object
 9   NAME_HOUSING_TYPE    36457 non-null  object
 10  DAYS_BIRTH           36457 non-null  int64
 11  DAYS_EMPLOYED        36457 non-null  int64
 12  FLAG_MOBIL           36457 non-null  int64
 13  FLAG_WORK_PHONE      36457 non-null  int64
 14  FLAG_PHONE           36457 non-null  int64
 15  FLAG_EMAIL           36457 non-null  int64
 16  OCCUPATION_TYPE      25134 non-null  object
 17  CNT_FAM_MEMBERS      36457 non-null  float64
 18  TARGET               36457 non-null  int64
dtypes: float64(2), int64(9), object(8)
memory usage: 5.3+ MB

In [16]:
data["TARGET"].value_counts()

TARGET
0    32166
1     4291
Name: count, dtype: int64

In [17]:
data.isnull().sum().sort_values(ascending=False)

OCCUPATION_TYPE        11323
CODE_GENDER                0
ID                         0
FLAG_OWN_CAR               0
FLAG_OWN_REALTY            0
AMT_INCOME_TOTAL           0
CNT_CHILDREN               0
NAME_EDUCATION_TYPE        0
NAME_FAMILY_STATUS         0
NAME_HOUSING_TYPE          0
NAME_INCOME_TYPE           0
DAYS_BIRTH                 0
DAYS_EMPLOYED              0
FLAG_WORK_PHONE            0
FLAG_MOBIL                 0
FLAG_PHONE                 0
FLAG_EMAIL                 0
CNT_FAM_MEMBERS            0
TARGET                     0
dtype: int64

In [18]:
(data.isnull().sum() / len(data) * 100).sort_values(ascending=False)

OCCUPATION_TYPE        31.058507
CODE_GENDER             0.000000
ID                      0.000000
FLAG_OWN_CAR            0.000000
FLAG_OWN_REALTY         0.000000
AMT_INCOME_TOTAL        0.000000
CNT_CHILDREN            0.000000
NAME_EDUCATION_TYPE     0.000000
NAME_FAMILY_STATUS      0.000000
NAME_HOUSING_TYPE       0.000000
NAME_INCOME_TYPE        0.000000
DAYS_BIRTH              0.000000
DAYS_EMPLOYED           0.000000
FLAG_WORK_PHONE         0.000000
FLAG_MOBIL              0.000000
FLAG_PHONE              0.000000
FLAG_EMAIL              0.000000
CNT_FAM_MEMBERS         0.000000
TARGET                  0.000000
dtype: float64

In [21]:
data["OCCUPATION_TYPE"] = data["OCCUPATION_TYPE"].fillna("Unknown")

In [22]:
data.isnull().sum().sort_values(ascending=False)

ID                     0
CODE_GENDER            0
FLAG_OWN_CAR           0
FLAG_OWN_REALTY        0
CNT_CHILDREN           0
AMT_INCOME_TOTAL       0
NAME_INCOME_TYPE       0
NAME_EDUCATION_TYPE    0
NAME_FAMILY_STATUS     0
NAME_HOUSING_TYPE      0
DAYS_BIRTH             0
DAYS_EMPLOYED          0
FLAG_MOBIL             0
FLAG_WORK_PHONE        0
FLAG_PHONE             0
FLAG_EMAIL             0
OCCUPATION_TYPE        0
CNT_FAM_MEMBERS        0
TARGET                 0
dtype: int64

In [23]:
data.head()

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,TARGET
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,Unknown,2.0,1
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,Unknown,2.0,1
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2.0,0
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0,0
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0,0

In [24]:
data["AGE"] = (-data["DAYS_BIRTH"] / 365).astype(int)
data["YEARS_EMPLOYED"] = (-data["DAYS_EMPLOYED"] / 365).astype(int)

In [25]:
data[["DAYS_BIRTH", "AGE", "DAYS_EMPLOYED", "YEARS_EMPLOYED"]].head()

   DAYS_BIRTH  AGE  DAYS_EMPLOYED  YEARS_EMPLOYED
0      -12005   32          -4542              12
1      -12005   32          -4542              12
2      -21474   58          -1134               3
3      -19110   52          -3051               8
4      -19110   52          -3051               8

In [26]:
data = data.drop(columns=["DAYS_BIRTH", "DAYS_EMPLOYED"])

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36457 entries, 0 to 36456
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   36457 non-null  int64
 1   CODE_GENDER          36457 non-null  object
 2   FLAG_OWN_CAR         36457 non-null  object
 3   FLAG_OWN_REALTY      36457 non-null  object
 4   CNT_CHILDREN         36457 non-null  int64
 5   AMT_INCOME_TOTAL     36457 non-null  float64
 6   NAME_INCOME_TYPE     36457 non-null  object
 7   NAME_EDUCATION_TYPE  36457 non-null  object
 8   NAME_FAMILY_STATUS   36457 non-null  object
 9   NAME_HOUSING_TYPE    36457 non-null  object
 10  FLAG_MOBIL           36457 non-null  int64
 11  FLAG_WORK_PHONE      36457 non-null  int64
 12  FLAG_PHONE           36457 non-null  int64
 13  FLAG_EMAIL           36457 non-null  int64
 14  OCCUPATION_TYPE      36457 non-null  object
 15  CNT_FAM_MEMBERS      36457 non-null  float64
 16  TARGET               36457 non-null  int64
 17  AGE                  36457 non-null  int64
 18  YEARS_EMPLOYED       36457 non-null  int64
dtypes: float64(2), int64(9), object(8)
memory usage: 5.3+ MB

In [28]:
categorical_cols = data.select_dtypes(include="object").columns
categorical_cols

Index(['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_INCOME_TYPE',
       'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE',
       'OCCUPATION_TYPE'],
      dtype='object')

In [29]:
data = pd.get_dummies(data, columns=categorical_cols, drop_first=True)

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36457 entries, 0 to 36456
Data columns (total 49 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   ID                                                 36457 non-null  int64
 1   CNT_CHILDREN                                       36457 non-null  int64
 2   AMT_INCOME_TOTAL                                   36457 non-null  float64
 3   FLAG_MOBIL                                         36457 non-null  int64
 4   FLAG_WORK_PHONE                                    36457 non-null  int64
 5   FLAG_PHONE                                         36457 non-null  int64
 6   FLAG_EMAIL                                         36457 non-null  int64
 7   CNT_FAM_MEMBERS                                    36457 non-null  float64
 8   TARGET                                             36457 non-null  int64
 9   AGE                                                36457 non-null  int64
 10  YEARS_EMPLOYED                                     36457 non-null  int64
 11  CODE_GENDER_M                                      36457 non-null  bool
 12  FLAG_OWN_CAR_Y                                     36457 non-null  bool
 13  FLAG_OWN_REALTY_Y                                  36457 non-null  bool
 14  NAME_INCOME_TYPE_Pensioner                         36457 non-null  bool
 15  NAME_INCOME_TYPE_State servant                     36457 non-null  bool
 16  NAME_INCOME_TYPE_Student                           36457 non-null  bool
 17  NAME_INCOME_TYPE_Working                           36457 non-null  bool
 18  NAME_EDUCATION_TYPE_Higher education               36457 non-null  bool
 19  NAME_EDUCATION_TYPE_Incomplete higher              36457 non-null  bool
 20  NAME_EDUCATION_TYPE_Lower secondary                36457 non-null  bool
 21  NAME_EDUCATION_TYPE_Secondary / secondary special  36457 non-null  bool
 22  NAME_FAMILY_STATUS_Married                         36457 non-null  bool
 23  NAME_FAMILY_STATUS_Separated                       36457 non-null  bool
 24  NAME_FAMILY_STATUS_Single / not married            36457 non-null  bool
 25  NAME_FAMILY_STATUS_Widow                           36457 non-null  bool
 26  NAME_HOUSING_TYPE_House / apartment                36457 non-null  bool
 27  NAME_HOUSING_TYPE_Municipal apartment              36457 non-null  bool
 28  NAME_HOUSING_TYPE_Office apartment                 36457 non-null  bool
 29  NAME_HOUSING_TYPE_Rented apartment                 36457 non-null  bool
 30  NAME_HOUSING_TYPE_With parents                     36457 non-null  bool
 31  OCCUPATION_TYPE_Cleaning staff                     36457 non-null  bool
 32  OCCUPATION_TYPE_Cooking staff                      36457 non-null  bool
 33  OCCUPATION_TYPE_Core staff                         36457 non-null  bool
 34  OCCUPATION_TYPE_Drivers                            36457 non-null  bool
 35  OCCUPATION_TYPE_HR staff                           36457 non-null  bool
 36  OCCUPATION_TYPE_High skill tech staff              36457 non-null  bool
 37  OCCUPATION_TYPE_IT staff                           36457 non-null  bool
 38  OCCUPATION_TYPE_Laborers                           36457 non-null  bool
 39  OCCUPATION_TYPE_Low-skill Laborers                 36457 non-null  bool
 40  OCCUPATION_TYPE_Managers                           36457 non-null  bool
 41  OCCUPATION_TYPE_Medicine staff                     36457 non-null  bool
 42  OCCUPATION_TYPE_Private service staff              36457 non-null  bool
 43  OCCUPATION_TYPE_Realty agents                      36457 non-null  bool
 44  OCCUPATION_TYPE_Sales staff                        36457 non-null  bool
 45  OCCUPATION_TYPE_Secretaries                        36457 non-null  bool
 46  OCCUPATION_TYPE_Security staff                     36457 non-null  bool
 47  OCCUPATION_TYPE_Unknown                            36457 non-null  bool
 48  OCCUPATION_TYPE_Waiters/barmen staff               36457 non-null  bool
dtypes: bool(38), float64(2), int64(9)
memory usage: 4.4 MB

In [31]:
X = data.drop("TARGET", axis=1)
y = data["TARGET"]

In [32]:
print(X.shape)
print(y.shape)

(36457, 48)
(36457,)

In [36]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [34]:
print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)

print("Training Labels   :", y_train.shape)
print("Testing Labels    :", y_test.shape)

Training Features : (29165, 48)
Testing Features  : (7292, 48)
Training Labels   : (29165,)
Testing Labels    : (7292,)

In [40]:
from sklearn.linear_model import LogisticRegression


lr = LogisticRegression(
    max_iter=1000,
    random_state=42,
    class_weight="balanced"
)
lr.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

In [41]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = lr.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.47956664838178825

In [42]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.47      0.62      6434
           1       0.12      0.54      0.20       858

    accuracy                           0.48      7292
   macro avg       0.50      0.50      0.41      7292
weighted avg       0.79      0.48      0.57      7292

In [43]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train, y_train)

print("Random Forest trained successfully!")

Random Forest trained successfully!

In [44]:
y_pred_rf = rf.predict(X_test)

from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred_rf))

Accuracy: 0.8624520021941854

In [45]:
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.92      0.93      0.92      6434
           1       0.40      0.36      0.38       858

    accuracy                           0.86      7292
   macro avg       0.66      0.64      0.65      7292
weighted avg       0.86      0.86      0.86      7292

In [46]:
print(confusion_matrix(y_test, y_pred_rf))

[[5983  451]
 [ 552  306]]

In [47]:
y_pred_rf = rf.predict(X_test)

from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred_rf))

Accuracy: 0.8624520021941854

In [48]:
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.92      0.93      0.92      6434
           1       0.40      0.36      0.38       858

    accuracy                           0.86      7292
   macro avg       0.66      0.64      0.65      7292
weighted avg       0.86      0.86      0.86      7292

In [49]:
print(confusion_matrix(y_test, y_pred_rf))

[[5983  451]
 [ 552  306]]

In [50]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=6,
    random_state=42,
    eval_metric="logloss"
)

xgb.fit(X_train, y_train)

print("XGBoost trained successfully!")

XGBoost trained successfully!

In [51]:
y_pred_xgb = xgb.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_xgb))

Accuracy: 0.8823368074602304

In [52]:
print(classification_report(y_test, y_pred_xgb))

              precision    recall  f1-score   support

           0       0.88      1.00      0.94      6434
           1       0.50      0.02      0.03       858

    accuracy                           0.88      7292
   macro avg       0.69      0.51      0.48      7292
weighted avg       0.84      0.88      0.83      7292

In [53]:
print(confusion_matrix(y_test, y_pred_xgb))

[[6421   13]
 [ 845   13]]

In [54]:
import joblib

joblib.dump(rf, "credit_card_model.pkl")

print("Model saved successfully!")

Model saved successfully!

In [55]:
joblib.dump(X.columns.tolist(), "feature_columns.pkl")

print("Feature names saved!")

Feature names saved!

In [56]:
model = joblib.load("credit_card_model.pkl")
columns = joblib.load("feature_columns.pkl")

print(type(model))
print(len(columns))

<class 'sklearn.ensemble._forest.RandomForestClassifier'>
48

In [57]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Create Decision Tree model
dt = DecisionTreeClassifier(random_state=42)

# Train the model
dt.fit(X_train, y_train)

# Predict
y_pred_dt = dt.predict(X_test)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred_dt))
print(classification_report(y_test, y_pred_dt))
print(confusion_matrix(y_test, y_pred_dt))

Accuracy: 0.8507953922106418
              precision    recall  f1-score   support

           0       0.92      0.91      0.92      6434
           1       0.37      0.39      0.38       858

    accuracy                           0.85      7292
   macro avg       0.64      0.65      0.65      7292
weighted avg       0.85      0.85      0.85      7292

[[5872  562]
 [ 526  332]]

# Conclusion

In this project, a Credit Card Approval Prediction System was developed using Machine Learning.

The dataset was collected, analyzed, preprocessed, and used to train four classification models:
- Logistic Regression
- Decision Tree
- Random Forest
- XGBoost

After comparing the models, the best-performing model was saved and integrated into a Flask web application. The application allows users to enter applicant details and instantly predicts whether a credit card application is approved or rejected.

This project demonstrates the complete Machine Learning pipeline from data collection to deployment.